from .auth.models import AuthAccess, AuthUserGroup, AuthGroup, AuthMenu
from .test import Test
from .master.models import (
    User, 
    RefJnsPegawai,
    RefJnsKawin,
    RefStatusHidup,
    Agama,
    Esselon,
    RumpunJabatan,
    Unor,
    RumpunJabatanJF,
    JenisJabatan,
    KelJabatan,
    RefHukdis,
    RefRiwayat,
    RefPenugasan,
    RefJabatanFungsional,
    RefJabatanFungsionalUmum,
    RefJenjangJabatan,
    RefJabatanStruktural,
    RefGolongan,
    RefDokumen,
    JenisInstansi,
    JenisInstansiId,
    Instansi,
    Satker,
    RefKPPN,
    RumpunPendidikan,
    RefTKPendidikan,
    RefPendidikan,
    RefJnsLokasi,
    RefLokasi
)
