"""update simpeg models

Revision ID: 03276d429203
Revises: db6dc2740609
Create Date: 2026-09-25 16:11:25.200123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '03276d429203'
down_revision: Union[str, Sequence[str], None] = 'db6dc2740609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_ref_jenjang_jabatan_kode_cepat'), table_name='ref_jenjang_jabatan')
    op.drop_column('ref_jenjang_jabatan', 'kode_cepat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_jenjang_jabatan', sa.Column('kode_cepat', mysql.VARCHAR(length=2), nullable=False))
    op.create_index(op.f('uq_ref_jenjang_jabatan_kode_cepat'), 'ref_jenjang_jabatan', ['kode_cepat'], unique=True)
    # ### end Alembic commands ###
