"""added model auth-all

Revision ID: 2bad1218d387
Revises: 
Create Date: 2026-06-14 14:19:57.983224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bad1218d387'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_group',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_group_created_by'), 'auth_group', ['created_by'], unique=False)
    op.create_index(op.f('ix_auth_group_id'), 'auth_group', ['id'], unique=False)
    op.create_table('auth_menu',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=30), nullable=True),
    sa.Column('color_icon', sa.String(length=30), nullable=True),
    sa.Column('color_text', sa.String(length=30), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['auth_menu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_menu_created_by'), 'auth_menu', ['created_by'], unique=False)
    op.create_index(op.f('ix_auth_menu_id'), 'auth_menu', ['id'], unique=False)
    op.create_index(op.f('ix_auth_menu_parent_id'), 'auth_menu', ['parent_id'], unique=False)
    op.create_table('auth_menu_access',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('auth_menu_id', sa.String(length=50), nullable=False, comment='di ambil dari id pada tabel auth_menu'),
    sa.Column('auth_group_id', sa.String(length=50), nullable=False, comment='di ambil dari id pada tabel auth_group'),
    sa.Column('createx', sa.Boolean(), nullable=True),
    sa.Column('readx', sa.Boolean(), nullable=True),
    sa.Column('updatex', sa.Boolean(), nullable=True),
    sa.Column('deletex', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['auth_group_id'], ['auth_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['auth_menu_id'], ['auth_menu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_group_id', 'auth_menu_id', name='uq_group_menu')
    )
    op.create_index(op.f('ix_auth_menu_access_auth_group_id'), 'auth_menu_access', ['auth_group_id'], unique=False)
    op.create_index(op.f('ix_auth_menu_access_auth_menu_id'), 'auth_menu_access', ['auth_menu_id'], unique=False)
    op.create_index(op.f('ix_auth_menu_access_created_by'), 'auth_menu_access', ['created_by'], unique=False)
    op.create_index(op.f('ix_auth_menu_access_id'), 'auth_menu_access', ['id'], unique=False)
    op.create_table('auth_user_group',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='id user dari db users'),
    sa.Column('auth_group_id', sa.String(length=50), nullable=False, comment='di ambil dari id pada tabel auth_group'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['auth_group_id'], ['auth_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_group_auth_group_id'), 'auth_user_group', ['auth_group_id'], unique=False)
    op.create_index(op.f('ix_auth_user_group_created_by'), 'auth_user_group', ['created_by'], unique=False)
    op.create_index(op.f('ix_auth_user_group_id'), 'auth_user_group', ['id'], unique=False)
    op.create_index(op.f('ix_auth_user_group_user_id'), 'auth_user_group', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_user_group_user_id'), table_name='auth_user_group')
    op.drop_index(op.f('ix_auth_user_group_id'), table_name='auth_user_group')
    op.drop_index(op.f('ix_auth_user_group_created_by'), table_name='auth_user_group')
    op.drop_index(op.f('ix_auth_user_group_auth_group_id'), table_name='auth_user_group')
    op.drop_table('auth_user_group')
    op.drop_index(op.f('ix_auth_menu_access_id'), table_name='auth_menu_access')
    op.drop_index(op.f('ix_auth_menu_access_created_by'), table_name='auth_menu_access')
    op.drop_index(op.f('ix_auth_menu_access_auth_menu_id'), table_name='auth_menu_access')
    op.drop_index(op.f('ix_auth_menu_access_auth_group_id'), table_name='auth_menu_access')
    op.drop_table('auth_menu_access')
    op.drop_index(op.f('ix_auth_menu_parent_id'), table_name='auth_menu')
    op.drop_index(op.f('ix_auth_menu_id'), table_name='auth_menu')
    op.drop_index(op.f('ix_auth_menu_created_by'), table_name='auth_menu')
    op.drop_table('auth_menu')
    op.drop_index(op.f('ix_auth_group_id'), table_name='auth_group')
    op.drop_index(op.f('ix_auth_group_created_by'), table_name='auth_group')
    op.drop_table('auth_group')
    # ### end Alembic commands ###
