"""update simpeg models1

Revision ID: db6dc2740609
Revises: 9e681a85b290
Create Date: 2026-09-19 23:24:06.340093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6dc2740609'
down_revision: Union[str, Sequence[str], None] = '9e681a85b290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_asn_jenis_jabatan',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('kode', sa.String(length=2), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_asn_jenis_jabatan_created_by'), 'ref_asn_jenis_jabatan', ['created_by'], unique=False)
    op.create_index(op.f('ix_ref_asn_jenis_jabatan_id'), 'ref_asn_jenis_jabatan', ['id'], unique=False)
    op.create_index(op.f('ix_ref_asn_jenis_jabatan_kode'), 'ref_asn_jenis_jabatan', ['kode'], unique=True)
    op.create_table('ref_level_kompetensi_asn',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('kode', sa.String(length=2), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_level_kompetensi_asn_created_by'), 'ref_level_kompetensi_asn', ['created_by'], unique=False)
    op.create_index(op.f('ix_ref_level_kompetensi_asn_id'), 'ref_level_kompetensi_asn', ['id'], unique=False)
    op.create_index(op.f('ix_ref_level_kompetensi_asn_kode'), 'ref_level_kompetensi_asn', ['kode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ref_level_kompetensi_asn_kode'), table_name='ref_level_kompetensi_asn')
    op.drop_index(op.f('ix_ref_level_kompetensi_asn_id'), table_name='ref_level_kompetensi_asn')
    op.drop_index(op.f('ix_ref_level_kompetensi_asn_created_by'), table_name='ref_level_kompetensi_asn')
    op.drop_table('ref_level_kompetensi_asn')
    op.drop_index(op.f('ix_ref_asn_jenis_jabatan_kode'), table_name='ref_asn_jenis_jabatan')
    op.drop_index(op.f('ix_ref_asn_jenis_jabatan_id'), table_name='ref_asn_jenis_jabatan')
    op.drop_index(op.f('ix_ref_asn_jenis_jabatan_created_by'), table_name='ref_asn_jenis_jabatan')
    op.drop_table('ref_asn_jenis_jabatan')
    # ### end Alembic commands ###
