"""modify table

Revision ID: f6ed76172e1d
Revises: 222220ba0d4b
Create Date: 2026-07-16 11:25:09.986224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6ed76172e1d'
down_revision: Union[str, Sequence[str], None] = '222220ba0d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenis_instansi',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('kode', sa.String(length=2), nullable=False),
    sa.Column('nama', sa.String(length=35), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jenis_instansi_created_by'), 'jenis_instansi', ['created_by'], unique=False)
    op.create_index(op.f('ix_jenis_instansi_id'), 'jenis_instansi', ['id'], unique=False)
    op.create_index(op.f('ix_jenis_instansi_kode'), 'jenis_instansi', ['kode'], unique=True)
    op.create_table('jenis_instansi_id',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('kode', sa.String(length=8), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jenis_instansi_id_created_by'), 'jenis_instansi_id', ['created_by'], unique=False)
    op.create_index(op.f('ix_jenis_instansi_id_id'), 'jenis_instansi_id', ['id'], unique=False)
    op.create_index(op.f('ix_jenis_instansi_id_kode'), 'jenis_instansi_id', ['kode'], unique=True)
    op.alter_column('ref_instansi', 'jenis',
               existing_type=mysql.ENUM('P', 'D'),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('ref_instansi', 'jenis_instansi_id',
               existing_type=mysql.ENUM('KO', 'KEMENT', 'LPNK', 'LNS', 'PROV', 'KAB', 'KOTA'),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.drop_index(op.f('ix_ref_instansi_kode'), table_name='ref_instansi')
    op.create_index(op.f('ix_ref_instansi_kode'), 'ref_instansi', ['kode'], unique=True)
    op.create_index(op.f('ix_ref_instansi_jenis'), 'ref_instansi', ['jenis'], unique=False)
    op.create_index(op.f('ix_ref_instansi_jenis_instansi_id'), 'ref_instansi', ['jenis_instansi_id'], unique=False)
    op.create_foreign_key(None, 'ref_instansi', 'jenis_instansi_id', ['jenis_instansi_id'], ['kode'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ref_instansi', 'jenis_instansi', ['jenis'], ['kode'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ref_instansi', type_='foreignkey')
    op.drop_constraint(None, 'ref_instansi', type_='foreignkey')
    op.drop_index(op.f('ix_ref_instansi_jenis_instansi_id'), table_name='ref_instansi')
    op.drop_index(op.f('ix_ref_instansi_jenis'), table_name='ref_instansi')
    op.drop_index(op.f('ix_ref_instansi_kode'), table_name='ref_instansi')
    op.create_index(op.f('ix_ref_instansi_kode'), 'ref_instansi', ['kode'], unique=False)
    op.alter_column('ref_instansi', 'jenis_instansi_id',
               existing_type=sa.String(length=8),
               type_=mysql.ENUM('KO', 'KEMENT', 'LPNK', 'LNS', 'PROV', 'KAB', 'KOTA'),
               existing_nullable=False)
    op.alter_column('ref_instansi', 'jenis',
               existing_type=sa.String(length=2),
               type_=mysql.ENUM('P', 'D'),
               existing_nullable=False)
    op.drop_index(op.f('ix_jenis_instansi_id_kode'), table_name='jenis_instansi_id')
    op.drop_index(op.f('ix_jenis_instansi_id_id'), table_name='jenis_instansi_id')
    op.drop_index(op.f('ix_jenis_instansi_id_created_by'), table_name='jenis_instansi_id')
    op.drop_table('jenis_instansi_id')
    op.drop_index(op.f('ix_jenis_instansi_kode'), table_name='jenis_instansi')
    op.drop_index(op.f('ix_jenis_instansi_id'), table_name='jenis_instansi')
    op.drop_index(op.f('ix_jenis_instansi_created_by'), table_name='jenis_instansi')
    op.drop_table('jenis_instansi')
    # ### end Alembic commands ###
